<?php
/**
 * @var \EricMartinez\Blog\Block\Post\ListPost $block
 */
$posts = $block->getPosts();
?>

<?php if ($posts && $posts->count()): ?>
    <div class="posts-list-container">
        <?php foreach ($posts as $post): ?>
            <a href="<?php echo $block->getUrl('blog/post/view', ['id' => $post->getId()]); ?>" class="post-card">
                <div class="post-card__image" style="background-image: url('<?= ($post->getCoverImage()) ? $block->getImageUrl($post->getCoverImage()) : 'https://placehold.co/600x220' ?>');"></div>
                <div class="post-card__content">
                    <h2 class="post-card__title">
                        <?php echo $block->escapeHtml($post->getTitle()); ?>
                    </h2>
                    <span class="post-card__read-more"><?php echo __('Read More'); ?> &rarr;</span>
                </div>
            </a>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <div class="message info empty">
        <span><?php echo __('There are no posts yet.'); ?></span>
    </div>
<?php endif; ?>
